### ISSUE TITLE
Error when clicking on database row (overhaul branch) for named instances

### ISSUE THREAD

**Issue by VictoriaD** [opserver/Opserver#140]
From the SQL Page, I clicked on an instance, then on databases at the top right, and then on one of the database rows. This is the error that came up:
![error1](https://cloud.githubusercontent.com/assets/14888476/13602737/55d0e6b4-e530-11e5-843f-bbedab1c2b3a.png)

When I click on the "Direct Link" shown in the error, it takes me to the Oh no! An Error! Page. Clicking through to the error log, and then the most recent error gets me this:

	Exceptions Log: Status
	The controller for path '/sql/sql/db/dbname/tables' was not found or does not implement IController.
	System.Web.HttpException

	System.Web.HttpException (0x80004005): The controller for path '/sql/sql/db/dbname/tables' was not found or does not implement IController.
	   at System.Web.Mvc.DefaultControllerFactory.GetControllerInstance(RequestContext requestContext, Type controllerType)
	   at System.Web.Mvc.DefaultControllerFactory.CreateController(RequestContext requestContext, String controllerName)
	   at System.Web.Mvc.MvcHandler.ProcessRequestInit(HttpContextBase httpContext, IController& controller, IControllerFactory& factory)
	   at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
	   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
	   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
		

	occurred 58 secs ago on myservername (delete)
	Server Variables
	AUTH_TYPE	Forms
	CONTENT_LENGTH	0
	HTTP_REFERER	http://myservername/sql/databases?node=myinstancename
	HTTP_USER_AGENT	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0
	LOCAL_ADDR	**.***.***.***
	REMOTE_ADDR	**.***.***.***
	REMOTE_HOST	**.***.***.***
	REQUEST_METHOD	GET
	URL	/sql/sql/db/dbname/tables
	URL and Query	http://myservername/sql/sql/db/dbname/tables
	Custom - Error while gathering custom data
	GetCustomData threw an exception:

	System.NullReferenceException: Object reference not set to an instance of an object.
	   at StackExchange.Opserver.GlobalApplication.GetCustomErrorData(Exception ex, HttpContext context, Dictionary`2 data)
	   at StackExchange.Exceptional.ErrorStore.LogException(Exception ex, HttpContext context, Boolean appendFullStackTrace, Boolean rollupPerServer, Dictionary`2 customData, String applicationName)

	Cookies
	.ADTkn	
	RequestHeaders
	Accept	text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
	Accept-Encoding	gzip, deflate
	Accept-Language	en-GB,en;q=0.5
	Connection	keep-alive
	Host	myservername
	Referer	http://myservername/sql/databases?node=myinstancename
	User-Agent	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0
	Exceptional 1.0.0.122
	Memory Error Store
	Server time is 08/03/2016 13:20:15

**Comment by VictoriaD** [comment]
I did a little more clicking, and this error comes up for instances with a \ in them, but instances without are loading the tables table with no problems!

**Comment by win32nipuh** [comment]
Try to get the latest version and check it again. It was fixed yesterday.

**Comment by VictoriaD** [comment]
I've downloaded the current version from overhaul, and now I get the following error on running. I have also removed all named instances from my SqlSettings file, and still get the same error.

	Server Error in '/' Application.

	Object reference not set to an instance of an object. 
	  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

	 Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

	Source Error: 



	Line 6:  @{
	Line 7:      Layout = null;
	Line 8:      var issues = IssueProvider.GetIssues();
	Line 9:  }
	Line 10: @functions
	  

	 Source File:  C:\inetpub\opserver\Views\Shared\IssuesList.cshtml    Line:  8 

	Stack Trace: 



	[NullReferenceException: Object reference not set to an instance of an object.]
	   StackExchange.Opserver.Data.SQL.SQLCluster..cctor() +50

	[TypeInitializationException: The type initializer for 'StackExchange.Opserver.Data.SQL.SQLCluster' threw an exception.]
	   StackExchange.Opserver.Data.SQL.<GetIssues>d__2.MoveNext() +113
	   System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +452
	   System.Linq.Enumerable.ToList(IEnumerable`1 source) +70
	   StackExchange.Opserver.Data.<>c__DisplayClass2_0.<GetIssues>b__1(IIssuesProvider p) +164
	   System.Threading.Tasks.<>c__DisplayClass9`1.<ForWorker>b__11() +1245
	   System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask) +32
	   System.Threading.Tasks.<>c__DisplayClass0.<ExecuteSelfReplicating>b__1(Object ) +277

	[AggregateException: One or more errors occurred.]
	   System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) +4445696
	   System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) +13873377
	   System.Threading.Tasks.Parallel.ForWorker(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally) +1403
	   System.Threading.Tasks.Parallel.ForEachWorker(IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally) +400
	   System.Threading.Tasks.Parallel.ForEach(IEnumerable`1 source, Action`1 body) +159
	   StackExchange.Opserver.Data.<>c.<GetIssues>b__2_0(List`1 old, MicroContext ctx) +180
	   StackExchange.Opserver.ExtensionMethods.GetSet(LocalCache cache, String key, Func`3 lookup, Int32 durationSecs, Int32 serveStaleDataSecs) +849
	   StackExchange.Opserver.Data.IssueProvider.GetIssues() +256
	   ASP._Page_Views_Shared_IssuesList_cshtml.Execute() in C:\inetpub\opserver\Views\Shared\IssuesList.cshtml:8
	   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +253
	   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +148
	   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +122
	   StackExchange.Profiling.Mvc.WrappedView.Render(ViewContext viewContext, TextWriter writer) +193
	   System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData) +137
	   ASP._Page_Views_Shared_Master_cshtml.Execute() in C:\inetpub\opserver\Views\Shared\Master.cshtml:47
	   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +253
	   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +148
	   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +122
	   System.Web.WebPages.<>c__DisplayClass3.<RenderPageCore>b__2(TextWriter writer) +311
	   System.Web.WebPages.WebPageBase.Write(HelperResult result) +108
	   System.Web.WebPages.WebPageBase.RenderSurrounding(String partialViewName, Action`1 body) +89
	   System.Web.WebPages.WebPageBase.PopContext() +310
	   StackExchange.Profiling.Mvc.WrappedView.Render(ViewContext viewContext, TextWriter writer) +193
	   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +375
	   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +90
	   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +833
	   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +81
	   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +186
	   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +38
	   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
	   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +65
	   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +53
	   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
	   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38
	   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +44
	   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +65
	   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38
	   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +399
	   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +157

	  


	Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.81.0

**Comment by kshyju** [comment]
@VictoriaD Can you check again (with latest code) and see whether you still have this error ? I verified with sql instanace names which has `\ ` in it and it totally works for me.

```
 {
    "name": "myFriendlyName",
    "connectionString": "Data Source=MyServer\\SQL2012_DEV;Initial Catalog=Peace;User ID=yes;Password=no"
 }
```

**Comment by VictoriaD** [comment]
Tried this again today, and it's now working fine. Thanks!
